# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: nadamq
  version: {{ GIT_DESCRIBE_TAG[1:] }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - c-array-defs >=0.2.post3
    - cython
    - future
    - libpython # [win]
    - mingw # [win]
    - nose
    - numpy
    # .. versionadded:: 0.14
    - or-event
    - path_helpers
    - paver
    - python
    - ragel
    - scons
    - si-prefix

  run:
    - python
    - c-array-defs >=0.2.post3
    # ..versionchanged:: 0.12.1
    #     See issue 2.
    - mingw # [win]
    - numpy
    # .. versionadded:: 0.14
    - or-event
    - si-prefix

test:
  imports:
    - nadamq
    - nadamq.NadaMq

about:
  home: http://github.com/wheeler-microfluidics/nadamq
  license: MIT
