{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'nadamq' %}
{% set MODULE_NAME = 'nadamq' %}
{% set LIB_NAME = 'NadaMQ' %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script:
    # Create Cpp files and copy Arduino library files to Conda Arduino library.
    - python file_handler.py {{ SRC_DIR }} {{ PREFIX }} {{ MODULE_NAME }} {{ LIB_NAME }}
    # Run setup
    - python setup.py install --single-version-externally-managed --record record.txt
    # Run build tests
#    - nosetests -v nadamq\tests # [win]
#    - nosetests -v nadamq/tests # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - python >=3.8
    - ragel # [win]
    - versioneer
    - pint
    - numpy
    - cmake
    - cython
    - pyserial
    - or-event
    - path-helpers
    - platformio-helpers
    - dropbot-headers


outputs:
  - name: {{ PKG_NAME }}-dev
    noarch: generic
    files:
      - share
    requirements:
      run:
        - dropbot-headers
  - name: {{ PKG_NAME }}
    platform: {{ target_platform }}
    files:
      - Lib/site-packages/{{ MODULE_NAME }} # [win]
      - {{ PREFIX }}/lib/python{{ python }}/site-packages/{{ MODULE_NAME }} # [unix]
    requirements:
      run:
        - python >=3.8
        - {{ pin_subpackage(PKG_NAME + '-dev', max_pin='x.x') }}
        - pint
        - numpy
        - pyserial
        - or-event
        - path-helpers
        - platformio-helpers
    test:
      imports:
        - {{ MODULE_NAME }}
        - {{ MODULE_NAME }}.{{ LIB_NAME }}

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: GPL
  summary: Embedded-friendly transport layer, inspired by ZeroMQ.

  # source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  path: ..
#  git_url: ../
