{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: nadamq
  #: .. versionchanged:: 0.15
  #:     Use git describe tag as version.  If not on a tag, append
  #:     `.post<describe number>`.
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    #: .. versionadded:: 0.15
    - {{ compiler('c') }}
    - ragel

  #: .. versionadded:: 0.15.2
  #:     Fix `#4 <https://github.com/sci-bots/nadamq/issues/4>`_.
  host:
    - c-array-defs >=0.2.post3
    - cython
    - future
    - nose
    - numpy
    #: .. versionadded:: 0.14
    - or-event
    - path_helpers
    - paver
    - si-prefix
    - scons
    #: .. versionchanged:: 0.15
    - python
    #: .. versionadded:: 0.15
    #: .. versionchanged:: 0.15.3
    #:     Move to ``requirements.host``.
    - msinttypes  # [win and py2k]

  run:
    #: .. versionadded:: 0.15
    - future
    #: .. versionchanged:: 0.15
    - python
    - c-array-defs >=0.2.post3
    - numpy
    #: .. versionadded:: 0.14
    - or-event
    - si-prefix

test:
  imports:
    - nadamq
    - nadamq.NadaMq

about:
  home: https://github.com/sci-bots/nadamq
  license: MIT
